# When the `gradlew assembleStubRelease` command is run, an APK is generated. If installed, it would silently exit upon running due to having no bytecode attached. It also has the package name com.samtupy.nvgt.stub, which is not ideal.
# Thus, given gradle's intermediate build outputs, we will generate not an APK, but the skeliton of one with .flat resources and a plaintext AndroidManifest.xml which will be rebuilt with a user's custom package name by nvgt. Literally if we didn't need to rename com.samtupy.nvgt.stub to com.user.theirgame, this entire fiasco would be entirely unneeded, we could just use the APK generated by gradle simply adding bytecode.bin to it and re-signing it. *sigh I suppose such is not to be though, would love someone to come along and show me a better way of doing this sans modifying the bytes of resources.arsc and the binary AndroidManifest.xml directly.
# If Gradle's intermediate build directory proves to be too unstable across versions and operating systems, we'll rework this script to read as much as possible directly from Gradle's output APK file instead of the intermediate build outputs used to create it.
# NVGT - NonVisual Gaming Toolkit (https://nvgt.dev)
# Copyright (c) 2022-2026 Sam Tupy
# license: zlib

import glob as _glob, os, sys, zipfile

if len(sys.argv) < 4:
	print("makestub: needed variant name, path to build directory, and path to built APK")
	sys.exit(1)
variant = sys.argv[1]
variant_cap = variant[0].upper()+ variant[1:]
build_dir = sys.argv[2]
apk_path = sys.argv[3]
gradle_user_home = sys.argv[4] if len(sys.argv) >= 5 else os.environ.get("GRADLE_USER_HOME", os.path.join(os.path.expanduser("~"), ".gradle"))
is_iap = "Iap" in variant_cap
is_debug = not variant.endswith("Release")

# Collect ALL aapt2 flat resource files for this variant from build/intermediates.
# AGP 8.x may distribute flat files across multiple subdirectories depending on
# dependency type (e.g. AAR deps like billing→androidx.core may not land in merged_res).
# We scan every intermediate subdirectory so nothing gets missed.
flat_files = {}  # basename -> filesystem path; merged_res wins on duplicates

def collect_flats(search_dir):
	if not os.path.isdir(search_dir):
		return
	for root, dirs, files in os.walk(search_dir):
		for f in files:
			if f.endswith(".flat") and f not in flat_files:
				flat_files[f] = os.path.join(root, f)

# Primary source first so it wins deduplication
collect_flats(os.path.join(build_dir, "intermediates", "merged_res", variant))

intermediates = os.path.join(build_dir, "intermediates")
if os.path.isdir(intermediates):
	for subdir in sorted(os.listdir(intermediates)):
		if subdir == "merged_res":
			continue
		collect_flats(os.path.join(intermediates, subdir, variant))

# AGP 8.x stores some compiled AAR dependency resources (such as billing assets
# needed by the IAP variant) in Gradle's transform cache rather than
# build/intermediates/. build/intermediates/ is always collected first above so
# f not in flat_files ensures project resources win over anything found here.
# Gradle <8.11: caches/transforms-N/, >=8.11: caches/{ver}/transforms/.
if is_iap:
	caches_dir = os.path.join(gradle_user_home, "caches")
	transforms_roots = (
		_glob.glob(os.path.join(caches_dir, "transforms-*")) +
		_glob.glob(os.path.join(caches_dir, "*", "transforms"))
	)
	for transforms_dir in transforms_roots:
		if not os.path.isdir(transforms_dir): continue
		for entry in os.scandir(transforms_dir):
			if not entry.is_dir(): continue
			for root, dirs, files in os.walk(os.path.join(entry.path, "transformed")):
				for f in files:
					if f.endswith(".flat") and f not in flat_files:
						flat_files[f] = os.path.join(root, f)

os.makedirs(os.path.join(build_dir, "tmp"), exist_ok=True)
res_zip_path = os.path.join(build_dir, "tmp", "res.zip")
with zipfile.ZipFile(res_zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
	for arc_name, fs_path in flat_files.items():
		zf.write(fs_path, arc_name)

# Collect root files — classpath resources loaded at
# runtime via ClassLoader.getResourceAsStream(), not AssetManager.
# Primary source: build/intermediates/merged_java_res/{variant}/out.jar produced by
# MergeJavaResourceTask, which is exactly what AGP packages into the APK root.
# Fallback: read directly from the built APK (strips signature files).
SIGNATURE_ENTRIES = {"META-INF/MANIFEST.MF"}
def is_apk_root_entry(name):
	if name.startswith("res/") or name.startswith("lib/"): return False
	if name in ("resources.arsc", "AndroidManifest.xml"): return False
	if name.startswith("classes") and name.endswith(".dex"): return False
	if name in SIGNATURE_ENTRIES: return False
	if name.startswith("META-INF/") and (name.endswith(".SF") or name.endswith(".RSA") or name.endswith(".DSA")): return False
	return True

root_files = {}  # archive path -> bytes
merged_java_res = os.path.join(build_dir, "intermediates", "merged_java_res", variant, "out.jar")
if os.path.isfile(merged_java_res):
	with zipfile.ZipFile(merged_java_res, "r") as jar:
		for entry in jar.namelist():
			if is_apk_root_entry(entry):
				root_files[entry] = jar.read(entry)
elif os.path.isfile(apk_path):
	with zipfile.ZipFile(apk_path, "r") as apk:
		for entry in apk.namelist():
			if is_apk_root_entry(entry):
				root_files[entry] = apk.read(entry)

if not os.path.isdir(os.path.join(os.path.dirname(__file__), "..", "release", "stub")): os.mkdir(os.path.join(os.path.dirname(__file__), "..", "release", "stub"))
stub_filename = "nvgt_android" + ("_debug" if is_debug else "") + ("_iap" if is_iap else "") + ".bin"
zip_out = zipfile.ZipFile(os.path.join(os.path.dirname(__file__), "..", "release", "stub", stub_filename), "w", zipfile.ZIP_DEFLATED)
zip_out.write(res_zip_path, "res.zip")
for arc_path, data in root_files.items():
	zip_out.writestr("root/" + arc_path, data)
if os.path.isfile(os.path.join("build", "intermediates", "dex", variant, "mergeDex" + variant_cap, "classes.dex")):
	zip_out.write(os.path.join("build", "intermediates", "dex", variant, "mergeDex" + variant_cap, "classes.dex"),"classes.dex")
elif os.path.isdir(os.path.join("build", "intermediates", "dex", variant, "mergeProjectDex" + variant_cap)):
	dex_counter = 1
	for root, dirs, files in os.walk(os.path.join("build", "intermediates", "dex", variant, "mergeProjectDex" + variant_cap)):
		for f in files:
			if not f.endswith(".dex"): continue
			zip_out.write(os.path.join(root, f), "classes" + (str(dex_counter) if dex_counter > 1 else "") + ".dex")
			dex_counter += 1
zip_out.write(os.path.join(build_dir, "intermediates", "merged_manifests", variant, f"process{variant_cap}Manifest", "AndroidManifest.xml"),"AndroidManifest.xml")
native_libpath = os.path.join(build_dir, "intermediates", "stripped_native_libs", variant, f"strip{variant_cap}DebugSymbols", "out", "lib")
for root, dirs, files in os.walk(native_libpath):
	for f in files:
		zip_out.write(os.path.join(root, f), os.path.join(root[len(native_libpath)-3:], f))
zip_out.close()
os.remove(res_zip_path)
