set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
if(PORT STREQUAL "sdl3" OR PORT MATCHES "libarchive" OR PORT MATCHES "libgit2")
	set(VCPKG_LIBRARY_LINKAGE dynamic)
else()
	set(VCPKG_LIBRARY_LINKAGE static)
endif()
set(VCPKG_CMAKE_SYSTEM_NAME Android)
set(VCPKG_CMAKE_SYSTEM_VERSION 28)
set(VCPKG_MAKE_BUILD_TRIPLET "--host=aarch64-linux-android")
# CMAKE_SHARED_LINKER_FLAGS forces 16KB ELF segment alignment on vcpkg-built shared libs (libSDL3.so)
# -> required by Google Play's 16 KB page size rule (Nov 2025) for apps targeting Android 15+.
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DANDROID_ABI=arm64-v8a -DANDROID_STL=c++_shared -DCMAKE_POLICY_VERSION_MINIMUM=3.15 "-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384")
